---
- name: Install the apache web service
  hosts: "{{ hostlist | default('all') }}"
  become: True
  vars:
    web_content: "Default web content from {{ inventory_hostname }}"

  tasks:
    - name: Ensure firewalld is installed
      ansible.builtin.dnf:
        name: firewalld
        state: installed

    - name: Ensure firewalld is enabled and started
      ansible.builtin.service:
        name: firewalld
        enabled: True
        state: started

    - name: Ensure firewall ports are open
      ansible.builtin.firewalld:
        immediate: True
        permanent: True
        service: "{{ item }}"
        state: enabled
      notify: Restart firewalld
      with_items:
        - "http"
        - "https"

    - name: Ensure apache is installed
      ansible.builtin.dnf:
        name: httpd
        state: present
      notify: Restart httpd

    - name: Ensure message is in index.html file
      ansible.builtin.copy:
        content: "{{ web_content }}"
        dest: /var/www/html/index.html

    - name: Show website address
      ansible.builtin.debug:
        msg: http://{{ ansible_host }}

  handlers:
    - name: Restart firewalld
      ansible.builtin.service:
        name: firewalld
        state: restarted

    - name: Restart httpd
      ansible.builtin.service:
        enabled: True
        name: httpd
        state: restarted
