---
# Example after_order playbook to use a variable defined in the order playbook

- name: Pre-order playbook
  hosts: localhost
  gather_facts: yes
  tasks:
    - debug:
        msg: "After-order playbook"

    block:
      - debug:
          msg: "The color you chose is {{ after_data }}."
    when: favorite_color is defined

    block:
      - debug:
          msg: "Nothing was ordered..."
    when: favorite_color is not defined
