---
- name: Check logging of variables
  hosts: localhost
  tasks:
    - name: Print credentials from a custom credential
      debug:
        msg: "Custom username/password: {{ custom_username }}/{{ custom_password }}"

    - name: Print credentials from a custom credential (no_log specified)
      debug:
        msg: "Custom username/password: {{ custom_username }}/{{ custom_password }}"
      no_log: True
