---
- name: Initiate an OpenSCAP scan via Insights
  hosts: all
#  hosts: "{{ target_host | default('NO_HOSTS')}}"
  become: True

  tasks:
    - name: Ensure OpenSCAP software is installed
      package:
        name: "{{ item }}"
      with_items:
        - openscap-scanner
        - scap-security-guide

    - name: Initiate scan
      command: "insights-client --compliance"
