---
- name: Initiate an Insights scan
  hosts: hosts: "{{ hostlist | default('all') }}"
  become: true

  tasks:
    - name: Stop the play if the host is not a Red Hat system
      ansible.builtin.meta: end_host
      when: ansible_facts['os_family'] is not defined or ansible_facts['os_family'] != "RedHat"     # Other options: Windows, Darwin

    - name: Initiate scan
      ansible.builtin.command: "insights-client"
