---
- name: Initiate an OpenSCAP scan via Insights
  hosts: "{{ hostlist | default('all') }}"
  become: True

  tasks:

    - name: Perform malware scan
      command: insights-client --collector malware-detection
      when: ansible_facts.distribution_major_version != "7"
