---
- name: Initiate a malware scan via Insights
  hosts: "{{ hostlist | default('all') }}"
  become: true

  tasks:
    - name: Stop the play if the host is not a Red Hat system
      ansible.builtin.meta: end_host
      when: ansible_facts['os_family'] is not defined or ansible_facts['os_family'] != "RedHat"     # Other options: Windows, Darwin

    - name: Perform malware scan
      ansible.builtin.command: insights-client --collector malware-detection
      when: ansible_facts.distribution_major_version != "7"
