---
- name: Apply a message of the day
  hosts: all
  become: True

  tasks:

    - name: Ensure the motd is applied
      include_role:
        name: motd
      vars:
        custom_motd: "Default MOTD message set from the playbook. Override this variable (custom_motd) to customize."
