---
- name: Ensure Red Hat Web Console (Cockpit) is installed and configured
  hosts: "{{ hostlist | default('all') }}"
  become: true

  tasks:
    - name: Stop the play if the host is not a Red Hat system
      ansible.builtin.meta: end_host
      when: ansible_facts['os_family'] is not defined or ansible_facts['os_family'] != "RedHat"     # Other options: Windows, Darwin

    - name: Ensure proper software is installed
      package:
        name: "{{ cockpit_packages }}"
      vars:
        cockpit_packages:
          - "cockpit*"
          - composer-cli
          - bash-completion
          - firewalld

    - name: Ensure Image Builder is started and enabled on reboot
      service:
        enabled: True
        name: osbuild-composer.socket
        state: started

    - name: Ensure web console is started and enabled on reboot
      service:
        enabled: True
        name: cockpit.socket
        state: started

    - name: Ensure firewall is configured for the web console
      ansible.posix.firewalld:
        immediate: True
        permanent: yes
        service: cockpit
        state: enabled
