---
# Notes:
#
# In order to pass in a boolean value on the command line, use this syntax (with the "=" sign)
#
# ansible-playbook register_rhportal.yml -e "perform_update=False"
#
#       If you use the ":" syntax, the variable will evaluate to True and the updates will be performed
#
#       ansible-playbook register_rhportal.yml -e "perform_update:False"
#
# In order to add extras repositories to be enabled, specify the role variable rhportal_reg_rhsm_supplemental_repo_list, e.g.
#
# ansible-playbook register_rhportal.yml -e '{"rhportal_reg_rhsm_supplemental_repo_list":["jws-5-for-rhel-8-x86_64-rpms"]}'

- name: Ensure systems are registered with access to required repositories
  hosts: "{{ hostlist | default('all') }}"
  become: true
  serial: 1
  vars:
    perform_update: False

  tasks:
    - name: Stop the play if the host is not a Red Hat system
      ansible.builtin.meta: end_host
      when: ansible_facts['os_family'] is not defined or ansible_facts['os_family'] != "RedHat"     # Other options: Windows, Darwin

    - name: Ensure RHSM registration
      include_role:
        name: rhportal_reg

    - name: Perform an update, if desired
      block:

      - name: Ensure kernel is up-to-date; if so a reboot will occur
        package:
          name: kernel
          state: latest
        register: kernel_status

#      - name: Reboot server if needed
#        include_role:
#          name: myreboot
#        vars:
#          myreboot_timeout: 240
#        when: kernel_status.changed

      - name: Reboot server if needed
        ansible.builtin.reboot:
        when: kernel_status.changed

      - name: Ensure all packages are updated
        package:
          name: '*'
          state: latest

      when: perform_update|bool
