---
- name: Register system with Satellite
  hosts: "{{ vm_fq_hostname | default('NO_HOSTS')}}"
  remote_user: root

  tasks:

    - name: Block for RHEL 7 systems
      block:

      - name: Define RHEL 7 activation key
        set_fact:
          Activation_Key: "Development-RHEL-7server-AK"

      when: ansible_facts.distribution == "RedHat" and ansible_facts.distribution_major_version == "7"

    - name: Block for RHEL 8 systems
      block:

      - name: Define RHEL 8 activation key
        set_fact:
          Activation_Key: "Development-RHEL-8server-AK"

      when: ansible_facts.distribution == "RedHat" and ansible_facts.distribution_major_version == "8"

    - name: Ensure Satellite registration
      include_role:
        name: satellite_reg
      vars:
         satellite_reg_servername: sat.example.com
         satellite_reg_organization: "Aero"
         satellite_reg_activation_key: "{{ Activation_Key }}"
