---
- name: Register a system with a Satellite server
  hosts: all
  become: True

  tasks:

    - name: Ensure Satellite registration
      include_role:
        name: satellite_reg
      vars:
         satellite_consumer_name: "{{ inventory_hostname }}"
         satellite_reg_servername: sat.example.com
         satellite_reg_organization: "Default"
         satellite_reg_activation_key: "Specify_Your_Activation_Key"
