---
#
#  For reference:  To get back to the default subscription manager config on a client
#    subscription-manager config --server.hostname subscription.rhsm.redhat.com
#    subscription-manager config --server.prefix "/subscription"
#    subscription-manager config --rhsm.baseurl https://cdn.redhat.com
#    subscription-manager config --rhsm.full_refresh_on_yum 0
#    subscription-manager config --rhsm.package_profile_on_trans 0
#    subscription-manager config --rhsm.repo_ca_cert /etc/rhsm/ca/redhat-uep.pem
#
- name: Register a system with a Satellite server
  hosts: "{{ hostlist | default('all') }}"
  become: True

  tasks:

    - name: Print registration info
      debug:
        msg: "Registering {{ inventory_hostname }} with Satellite server {{ satellite_reg_servername }}"

    - name: Ensure Satellite registration
      include_role:
        name: satellite_reg
      vars:
         satellite_reg_consumer_name: "{{ inventory_hostname }}"
         satellite_reg_server_insecure: False
#         satellite_reg_servername: "{{ satellite_reg_servername }}"
#         satellite_reg_organization: "{{ satellite_reg_organization }}"
#         satellite_reg_activation_key: "{{ satellite_reg_activation_key }}"

    - name: Print server public key info
      debug:
        msg: "Retrieving ssh public key from {{ satellite_reg_servername }} and installing to user {{ ansible_user }} for remote execution"

    - name: Retrieve public key from the Satellite server
      ansible.builtin.uri:
        return_content: true
        status_code:
          - 200
        url: "https://{{ satellite_reg_servername }}:9090/ssh/pubkey"
      register: ssh_info

    - name: Print ssh public key
      debug:
        var: ssh_info.content
        verbosity: 1

    - name: Populate the authorized_key file
      ansible.posix.authorized_key:
        key: "{{ ssh_info.content }}"
        state: present
        user: "{{ ansible_user }}"
