---
- name: Ensure systems are unregistered from Red Hat subscription management
  hosts: "{{ hostlist | default('all') }}"
  become: True

  tasks:
    - name: Ensure systems are unregistered
      community.general.redhat_subscription:
        state: absent
