---
- name: Ensure systems are unregistered from Red Hat Insights
#  hosts: "{{ target_host | default('NO_HOSTS')}}"
  hosts: all
  become: True

  tasks:
    - name: Ensure systems are unregistered
      command: insights-client --unregister
