---
- name: Ensure systems are unregistered from Red Hat subscription management
#  hosts: "{{ target_host | default('NO_HOSTS')}}"
  hosts: all
  become: True

  tasks:
    - name: Ensure systems are unregistered
      community.general.redhat_subscription:
        state: absent
