---
- name: Ensure systems are unregistered
  hosts: "{{ target_host | default('NO_HOSTS')}}"
  become: True

  tasks:
    - name: Ensure systems are unregistered
      community.general.redhat_subscription:
        state: absent
