---
- name: Update RHEL systems and reboot if needed
  hosts: "{{ hostlist | default('all') }}"
#  become: true

  tasks:
    - name: Stop the play if the host is not a Red Hat system
      ansible.builtin.meta: end_host
      when: ansible_facts['os_family'] is not defined or ansible_facts['os_family'] != "RedHat"     # Other options: Windows, Darwin

    - name: Block to perform update/reboot
      block:
        - name: Ensure kernel is up-to-date; if so a reboot will occur
          ansible.builtin.package:
            name: kernel
            state: latest
          register: kernel_status

        - name: Reboot server if needed
          ansible.builtin.reboot:
          when: kernel_status.changed

#        - name: Reboot server if needed
#          include_role:
#            name: myreboot
#          vars:
#        myreboot_timeout: 240
#          when: kernel_status.changed

        - name: Ensure all packages are updated
          ansible.builtin.package:
            name: '*'
            state: latest

      become: true
