# Import required roles
- src: https://github.com/t-prinz/satellite_reg
- src: https://github.com/t-prinz/rhportal_reg
#- src: https://github.com/t-prinz/myreboot
- src: https://github.com/t-prinz/motd.git
